language: generic 
sudo: required
services:
    - docker 

# Build testing container
before_install:
    - docker build -t edumenu/covid-tracker-container -f .

# Run Tests
script:
    - docker run -e CI=true edumenu/covid-tracker-container npm test -- --coverage

