language: generic 
sudo: required
services:
    - docker 

# Build testing container
before_install:
    - docker build -t edumenu/react-tailwindcss -f Dockerfile .

# Run Tests
script:
    - docker run -e CI=true edumenu/react-tailwindcss npm run test