sudo: required

language: node_js
node_js:
    - 10 
services:
    - docker 

# Build testing container
before_install:
    - docker build -t edumenu/react-tailwindcss -f Dockerfile.dev .
    - docker ps -a

# Run Tests
script:
    - docker run -e CI=true edumenu/react-tailwindcss npm run test -- --coverage