# Setting the base image for our container
FROM node:10.16.0-alpine

# Setting the working directory
WORKDIR '/app'

# Installing react app dependencies
COPY ./package.json ./
COPY package-lock.json ./
RUN npm install 
RUN npm install react-scripts@3.4.1
RUN npm install tailwindcss 

# Add a copy to the root of the app
COPY . . 

# Start the app
CMD ["npm", "run", "start"]