version: '3.7'

services:  # containers. same as docker run
  covid-tracker-react: # Container name
    stdin_open: true # docker run -i. Interactive mode (-it) to avoid react-scripits from exiting 
    tty: true        # docker run -t. Interactive mode (-it) to avoid react-scripits from exiting  
    build:
        context: .
        dockerfile: Dockerfile
    image: edumenu/react-tailwindcss
    ports: 
      - "3001:3000" # Port 3001 on host and 3000 to the other docker containers on the same network
    volumes:
      - '.:/app'  
      - '/app/node_modules'  # Anonymous volume to avoid overwritting 
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables polling mechanism to watch for live updates