FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
COPY package-lock.json ./
RUN npm install 
RUN npm install react-scripts@3.4.1
RUN npm install tailwindcss 
COPY . . 
CMD ["npm", "run", "start"]